{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]\n",
      "swarmauri SDK version: 0.4.3\n",
      "Gradio version: 4.26.0\n"
     ]
    }
   ],
   "source": [
    "# Display the versions of Python, swarmauri SDK, and Gradio\n",
    "import sys\n",
    "import swarmauri\n",
    "import gradio\n",
    "\n",
    "# Print the versions\n",
    "print(f\"Python version: {sys.version}\")\n",
    "print(f\"swarmauri SDK version: {swarmauri.__version__}\")\n",
    "print(f\"Gradio version: {gradio.__version__}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Import necessary libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:Subclass Parameter does not have a type annotation\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "import gradio as gr\n",
    "from swarmauri.standard.llms.concrete.GroqToolModel import GroqToolModel\n",
    "from swarmauri.standard.agents.concrete.ToolAgent import ToolAgent\n",
    "from swarmauri.standard.toolkits.concrete.AccessibilityToolkit import AccessibilityToolkit as Tool\n",
    "from swarmauri.standard.conversations.concrete.Conversation import Conversation\n",
    "from swarmauri.standard.toolkits.concrete.Toolkit import Toolkit"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Fetch the API key from environment variables or define it directly (Not recommended for production)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "load_dotenv()\n",
    "API_KEY = os.getenv('GROQ_API_KEY')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Initialize the GroqToolModel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "tool_model = GroqToolModel(api_key=API_KEY)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'llama3-groq-70b-8192-tool-use-preview'"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tool_model.name"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Create an AccessibilityTool"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "accessibility_tool = Tool(name=\"AccessibilityTool\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Use the tool within your toolkit\n",
    "toolkit = Toolkit(tools={\n",
    "    \"AutomatedReadabilityIndexTool\": accessibility_tool.automated_readability_index_tool,\n",
    "    \"ColemanLiauIndexTool\": accessibility_tool.coleman_liau_index_tool,  \n",
    "    \"FleschKincaidTool\": accessibility_tool.flesch_kincaid_tool,\n",
    "    \"FleschReadingEaseTool\": accessibility_tool.flesch_reading_ease_tool,\n",
    "    \"GunningFogTool\": accessibility_tool.gunning_fog_tool\n",
    "})"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Create a ToolAgent with the GroqToolModel, Conversation, and Toolkit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "tool_agent = ToolAgent(\n",
    "    llm=tool_model,\n",
    "    conversation=Conversation(),\n",
    "    toolkit=toolkit\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Define the function to be executed for the gradio interface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7860\n",
      "IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.\n",
      "--------\n",
      "Running on public URL: https://c4de7549c65d4527c5.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://c4de7549c65d4527c5.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 270, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 112, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 257, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 135, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 95, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2028, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2107, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2189, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2185, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2088, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 270, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 112, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 257, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 135, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 95, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2028, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2107, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2189, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2185, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2088, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 270, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 112, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 257, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 135, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 95, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 908, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2028, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2107, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2189, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2185, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 2088, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1029, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1058, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1378, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 655, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 929, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1038, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 558, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type\n"
     ]
    }
   ],
   "source": [
    "# Define the function to be executed for the Gradio interface\n",
    "def tool_agent_interface(input_text, history):\n",
    "    # Directly pass the input_text (string) to tool_agent.exec\n",
    "    result = tool_agent.exec(input_text)\n",
    "    return result\n",
    "\n",
    "# Initialize the Gradio interface\n",
    "demo = gr.ChatInterface(tool_agent_interface)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(share=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "swarmauri(0.4.3)",
   "language": "python",
   "name": "swarmauri-0.4.3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
